name: Continuous Integration with GitHub, GitHub Actions and Docker Hub

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3

     - name: Log in to Docker Hub
       uses: docker/login-action@v3.0.0
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
       
     - name: Setup Node JS
       uses: actions/setup-node@v4
       with:
         node-version: '14'

     - name: Install Node Modules in Backend     
       working-directory: ./backend
       run: npm install

     - name: Install Node Modules in Frontend     
       working-directory: ./frontend
       run: npm install

     - name: Docker Compose Build
       working-directory: .
       run: docker compose build

     - name: Push to Docker Hub Container Registry
       run: |
         docker tag node-react-backend:latest ${{ secrets.DOCKER_USERNAME }}/node-react-backend:latest
         docker tag node-react-backend:latest ${{ secrets.DOCKER_USERNAME }}/node-react-backend:${{ github.run_id }}
         
         docker push ${{ secrets.DOCKER_USERNAME }}/node-react-backend:latest
         docker push ${{ secrets.DOCKER_USERNAME }}/node-react-backend:${{ github.run_id }}

         docker tag node-react-frontend:latest ${{ secrets.DOCKER_USERNAME }}/node-react-frontend:latest
         docker tag node-react-frontend:latest ${{ secrets.DOCKER_USERNAME }}/node-react-frontend:${{ github.run_id }}
         
         docker push ${{ secrets.DOCKER_USERNAME }}/node-react-frontend:latest
         docker push ${{ secrets.DOCKER_USERNAME }}/node-react-frontend:${{ github.run_id }}